@startuml
!pragma layout smetana
'https://plantuml.com/class-diagram
skinparam linetype polyline
skinparam linetype ortho

class Main{
+ static void main(String[] args)
}

class StartMenu {
+ startupInterface()
+ newGame()
+ continueGame()
+ exitGame()
+ chooseGender()
+ chooseName()
+ chooseStarterPokemon()
+ savePlayer()
+ choosePlayerName()
+ translatePlayerChoiceToPokeindex()
+

}


class Pokemon{
- int pokemonID
- int attackPower
- int defensePower
- int hp
- int lvl
- String name
- String typeOne
- String typeTwo
- String abilities
- String rarity
+ Pokemon()
+ getMaxHp()
+ getPokemonID()
+ getHp()
+ setHp()
+ getLvl()
+ getAttackPower()
+ getDefensePower()
+ getName()
+ getTypeOne()
+ getTypeTwo()
+ getAbilities()
+ getRarity()
+ restoreHP()
+ levelUp()
+ levelUp

}
class music{
- playMusic
- playMusicBattle
- playMusicStart
- playMusicPokeCenter
}

class Combat{
+ takeDamage()
+ giveDamage()
+ blackout()
+ battleRound
- performPlayerTurn
- performEnemyTurn
- finalizeBattle
- displayPlayerPokemonStatus
- displayEnemyPokemonStatus
+ dealDamage
+ calculateDamage
- calculateDefenseScaling
- typeMultiplier
- enemyDefeat
- PlayerPokemonFaint
- pokemonsDefeated
- playerDefeatPenalty
+ getRandomPokemon()
+ getRandomPokemonList()
+ getPrimaryPlayerPokemon
+ setPrimaryPlayerPokemon
+ getSpecificPokemonMewto()
+ getSpecificPokemonDarkrai()
+ getSpecificPokemonGyarados()
+ getPlayerPokemonList()
}

class CombatInterface{
+ combatOptions()
+ run()
+ fight()
+ bag()
+ switchPokemon()
+ catchPokemon()
+ combatRandom()
+ combat5to10()
+ combat10to25()
+ combat25to50()
+ caughtPokemon()
+ usePokeball()
+ viewBag()
+ displayBag()
+ changePokemonInParty()
+ switchPokemon()
+ random()
+ combatOptionsRed()
+ combatOptionsDarkrai()
+ combatOptionsGyarados()



}

class Player{
- name
- wallet
- Arraylist<Pokemon> pokeDex
- Arraylist<String> bag
+ Player()
+ getName()
+ setName()
+ getWallet()
+ setWallet()
+ Arraylist<Pokemon> getPokemonParty()
+ addItemToBag()
+ Arraylist<Item> getBag()
+ addFunds()
+ removeFunds()
+ removeItemFromBag()

}

class UserInterface {
- Explore explore = new Explore
- Town town = new Town
- Player player = new Player
+ userOptions()
+ pokeMartOptions()
+ TownOrPokeCenter()
+ Startmenu()
+ StartMenuOptions()
+ 
}

class Town {
+ pokeCenter()
+ pokeMart()
+ buy()
+ sell()
+
}

class Item{
- name
- price
+ Item()
+ getName()
+ getPrice()
+ toString()
}

class Explore {
- CombatInterface combat = new CombatInterface
+ random()
+ fishing()
+ findItem()
+ randomDialogue()
+ itemList()
+ explore()
+ gatesOfPokemon()
+ randomSelect()
+ exploreInterface()
+ random()
+ fishing()
+ itemInitializer()
+ findItem()
+ randomDialogue()
+ dialogLegendary()
+ dialogOldman()
+ dialogIdiotKid()
+ dialogFishingMan()
+ dialogGirlyTrainee()
+ showMagikarp()
+ showTreasureChest()
+ showPikachu()
+ showGyarados()
+ showDigglet()
+ addPokemonToPlayerPokemon()
}

class FileIO{
+ writeData()
+ loadData()
+ loadPokemonFromFile()
+ clearPlayerPokemonFile()
+ clearBagFile()
+ clearPlayerFile()
+ saveItemToBag()
+ saveItemsToBag()
+ savePokemonToPlayerPokemons()
+ Arraylist<Item> readItemsFromBag()
+ savePokemonData()
+ readPlayerData()
+ savePlayerData()
}
class TextUI{
- Scanner scanner = new Scanner
+ displayMsg()
+ userInput()
+ fishingmanTalk()
+ oldManTalk()

}

Main --> StartMenu
StartMenu --> UserInterface
UserInterface --> Player
UserInterface --> Town
UserInterface --> Explore
Explore --> CombatInterface
CombatInterface --> Combat
Pokemon ---> Player
Pokemon ---> Combat
StartMenu -> FileIO
TextUI -> StartMenu
TextUI --> UserInterface
TextUI --> Explore
TextUI --> CombatInterface


@enduml